repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: files/(issue|motd)
      - id: mixed-line-ending
        args:
          - '--fix=lf'
      - id: pretty-format-json
        args:
          - '--autofix'
      - id: requirements-txt-fixer
  - repo: 'https://github.com/igorshubovych/markdownlint-cli'
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args:
          - '--config=.mdl_config.yaml'
  - repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.28.0
    hooks:
      - id: yamllint
        args:
          - '--strict'
  - repo: 'https://github.com/cisagov/pre-commit-shfmt'
    rev: v0.0.2
    hooks:
      - id: shfmt
        args:
          - '-i'
          - '2'
          - '-bn'
          - '-ci'
          - '-sr'
  - repo: 'https://github.com/detailyang/pre-commit-shell'
    rev: 1.0.5
    hooks:
      - id: shell-lint
  - repo: 'https://github.com/pre-commit/mirrors-prettier'
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
  - repo: 'https://github.com/IamTheFij/docker-pre-commit'
    rev: v2.1.1
    hooks:
      - id: docker-compose-check
  - repo: 'https://github.com/antonbabenko/pre-commit-terraform'
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        exclude: ^examples/
      - id: checkov
  - repo: 'https://github.com/cisagov/pre-commit-packer'
    rev: v0.0.2
    hooks:
      - id: packer_validate
      - id: packer_fmt
  - repo: 'https://github.com/ansible-community/ansible-lint'
    rev: v6.10.0
    hooks:
      - id: ansible-lint
  - repo: 'https://github.com/python-jsonschema/check-jsonschema'
    rev: 0.19.2
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
