name: Build and Push Container Image to Registry

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - docker/*

permissions:
  contents: 'read'
  packages: 'write'

env: 
  DOCKER_REGISTRY: ghcr.io
  ORGANISATION_NAME: RukayaOK
  DOCKERFILE_PATH: docker/Dockerfile
  DOCKLE_HOST: "unix:///var/run/docker.sock"
  DOCKER_CONTENT_TRUST: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build Container Image 
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ${{ env.DOCKERFILE_PATH }}
      
      - name: Scan image
        uses: Azure/container-scan@v0
        with:
          image-name: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          severity-threshold: CRITICAL
          run-quality-checks: true
      
      - name: Push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ${{ env.DOCKERFILE_PATH }}